apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: todos-api-dev

resources:
  - namespace.yaml
  - ../../base

patches:
  - path: todos-api/todos-api-dev.yaml
    target:
      kind: Deployment
      name: todo-api
  - path: game-2048/game-2048-dev.yaml
    target:
      kind: Ingress
      name: game-2048
