apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev
  namespace: argocd
  annotations:
    notifications.argoproj.io/subscribe.on-health-degraded.gmail: zaafir.mougammadou-zaccaria@supdevinci-edu.fr
    notifications.argoproj.io/subscribe.on-sync-failed.gmail: zaafir.mougammadou-zaccaria@supdevinci-edu.fr
spec:
  project: default
  source:
    repoURL: https://github.com/admngn/555.git
    targetRevision: HEAD
    path: apps/overlays/dev
  destination:
    server: https://kubernetes.default.svc
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
